version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: crisis-postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: myappdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: crisis-backend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./:/app          # bind mount for hot reload
      - /app/node_modules # keep local node_modules separate
    depends_on:
      - postgres
    environment:
      PORT: 8080
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/myappdb?schema=public
      JWT_SECRET: 123456

volumes:
  postgres_data:
